### ISSUE TITLE
I can't install Plugin. "the application is not installed because it conflicts with another package". pls help

### ISSUE THREAD

**Issue by Alex3040252** [choiman1559/NotiSender-TelephonyPlugin#1]
I can't install Plugin. "the application is not installed because it conflicts with another package". pls help

**Comment by choiman1559** [comment]
Try with the new version: 1.0.5.

**Comment by Alex3040252** [comment]
the same story((

**Comment by Alex3040252** [comment]
I've got  installed "Anydesk" to manage remotely. May be it's the reason?

**Comment by choiman1559** [comment]
Could you try one more time with version 1.0.6?

**Comment by Alex3040252** [comment]
yippee! working. thanks a lot! I will try using
